name: Check links

permissions:
  contents: read

on:
  workflow_call:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: --skip-missing --glob-ignore-case --hidden --accept 200,429 --max-concurrency=1 --no-ignore './**/*.md' './**/*.html' './**/*.rst'
          fail: true
          format: markdown
          jobSummary: true