name: Code Quality Checks

on:
  push:
  pull_request:
  workflow_call:
    inputs:
      project-yaml:
        required: true
        type: string
        description: 'Project Yaml file that consists of build and check configurations'
      user-yaml:
        required: true
        type: string
        description: 'User Yaml file with list of build and checks to be executed'

defaults:
  run:
    shell: bash

jobs:
  setup:
    runs-on: ubuntu-24.04

    container:
      image: docker.io/ifxmakers/makers-docker:push
      volumes:
        - .:/myLocalWorkingDir:rw
      options: --cpus 1

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Checkout makers-devops
        uses: actions/checkout@v4
        with:
          repository: Infineon/makers-devops
          ref: fix-configs-path
          path: makers-devops

      - name: Set strategy matrix
        id: set-matrix
        run: |
          eval $(python3 makers-devops/tools/code_checks/codeChecks.py --projectYAML "${{ inputs.project-yaml }}" --userYAML "${{ inputs.user-yaml }}" --getAllChecks)

      - name: Append Code Checks Output to Summary
        run: |
          echo "## 📜 Code Quality Report" >> $GITHUB_STEP_SUMMARY

    outputs:
      checks: ${{ steps.set-matrix.outputs.checks }}
      

  codeChecks:
    runs-on: ubuntu-24.04
    needs: setup

    container:
      image: docker.io/ifxmakers/makers-docker:push
      volumes:
        - .:/myLocalWorkingDir:rw
      options: --cpus 1

    strategy:
      matrix:
        checks: ${{ fromJson(needs.setup.outputs.checks) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Checkout makers-devops
        uses: actions/checkout@v4
        with:
          repository: Infineon/makers-devops
          ref: fix-configs-path
          path: makers-devops

      - name: Set execute permissions for all .sh files in a folder
        run: |
          find extras/makers-devops/tools/code_checks/ -name "*.sh" -exec chmod +x {} \;

      - name: Run all code checks
        id: run_build
        if: success() || failure()
        run: |
          echo "Workflow has these parameters :"
          echo "matrix.checks   : ${{ matrix.checks }}"
          echo ""
          python3 makers-devops/tools/code_checks/codeChecks.py --projectYAML "${{ inputs.project-yaml }}" --userYAML "${{ inputs.user-yaml }}" --runCheck ${{ matrix.checks }}  > output.log
        continue-on-error: true

      - name: Archive code check reports
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.checks }}
          path: _results

      - name: Append Code Checks Output to Summary
        run: |
          echo "<details>" >> $GITHUB_STEP_SUMMARY
          cat output.log >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY

