name: Build docs

### QUICK REFERENCE ###

# Required project structure:
# docs/
#   requirements.txt
#   Makefile
#   ...

# How to call this workflow from another workflow:
# name: Build docs
# on:
#  ...
# jobs:
#  call-workflow:
#    uses: Infineon/makers-devops/.github/workflows/docs_build.yml@main

on:
  workflow_call:
    inputs:
      doxy-required:
        required: false
        type: boolean
        default: false
        description: 'Set to true if Doxygen is required for building the docs.'

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - name: Install Doxygen
      if: ${{ inputs.doxy-required }}
      run: sudo apt-get update && sudo apt-get install -y doxygen
    - name: Install required Python packages
      run: pip install -r docs/requirements.txt
    - name: Build docs from Makefile
      run: make -C docs/ html
    - name: Upload docs
      uses: actions/upload-artifact@v4
      with:
        name: html-docs
        path: docs/build/