name: HIL Checks

on:
  workflow_call:
    inputs:
      project-yaml:
        required: true
        type: string
        description: 'Project Yaml file that consists of build and check configurations'
      user-yaml:
        required: true
        type: string
        description: 'User Yaml file with list of build and checks to be executed'

defaults:
  run:
    shell: bash

# permissions:
#   contents: write
    
jobs:
  setup:
    runs-on: ubuntu-24.04

    container:
      image: docker.io/ifxmakers/makers-docker:latest

      # image: ghcr.io/infineon/makers-docker:latest
      # credentials:
      #   username: ${{ github.actor }}
      #   password: ${{ secrets.github_token }}

      volumes:
        - .:/myLocalWorkingDir:rw
      options: --cpus 1

    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set strategy matrix (get all hil checks)
        id: set-matrix
        run: |
          eval $(python3 extras/makers-devops/src/python/code_checks/codeChecks.py --projectYAML "${{ inputs.project-yaml }}" --userYAML "${{ inputs.user-yaml }}" --getAllHILChecks)

      - name: Append HIL Checks Output to Summary
        run: |
          echo "## 📜 Test Quality Report" >> $GITHUB_STEP_SUMMARY

    outputs:
      checks: ${{ steps.set-matrix.outputs.checks }}
      

  hilChecks:
    runs-on:
      - self-hosted
      - X64
      - Linux
    needs: setup

    strategy:
      fail-fast: false

      matrix:
        checks: ${{ fromJson(needs.setup.outputs.checks) }}

    steps:
      - name: Checkout repository (recursive submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-tags: true
          fetch-depth: 0

      - name: Run HIL check (${{ matrix.checks }})
        id: run_build
        run: |
          echo "Workflow has these parameters :"
          echo "matrix.checks   : ${{ matrix.checks }}"
          echo ""

          hilChecks.py --projectYAML "${{ inputs.project-yaml }}" --userYAML "${{ inputs.user-yaml }}" --runCheck ${{ matrix.checks }} --dockerTag=latest  2>&1 | tee output.log

      - name: Archive code check reports
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.checks }}
          path: _results

      - name: Append HIL checks output to summary
        if: success() || failure()
        run: |
          echo "<details>" >> $GITHUB_STEP_SUMMARY
          cat output.log >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY
